# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 03_ToRaster.py
# Created on: 2021-06-24 08:20:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.env.overwriteOutput = True

# Set Geoprocessing environments
arcpy.env.newPrecision = "SINGLE"
arcpy.env.autoCommit = "1000"
arcpy.env.XYResolution = ""
arcpy.env.processingServerUser = ""
arcpy.env.XYDomain = ""
arcpy.env.processingServerPassword = ""
arcpy.env.scratchWorkspace = "\\\\WURNET.NL\\Homes\\boeke015\\My Documents\\ArcGIS\\Default.gdb"
arcpy.env.cartographicPartitions = ""
arcpy.env.terrainMemoryUsage = "false"
arcpy.env.MTolerance = ""
arcpy.env.compression = "LZ77"
arcpy.env.coincidentPoints = "MEAN"
arcpy.env.randomGenerator = "0 ACM599"
arcpy.env.outputCoordinateSystem = ""
arcpy.env.rasterStatistics = "STATISTICS 1 1"
arcpy.env.ZDomain = ""
arcpy.env.transferDomains = "false"
arcpy.env.maintainAttachments = "true"
arcpy.env.resamplingMethod = "NEAREST"
arcpy.env.snapRaster = ""
arcpy.env.projectCompare = "NONE"
arcpy.env.cartographicCoordinateSystem = ""
arcpy.env.configKeyword = ""
arcpy.env.outputZFlag = "Same As Input"
arcpy.env.qualifiedFieldNames = "true"
arcpy.env.tileSize = "128 128"
arcpy.env.parallelProcessingFactor = ""
arcpy.env.pyramid = "PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP"
arcpy.env.referenceScale = ""
arcpy.env.processingServer = ""
arcpy.env.extent = "DEFAULT"
arcpy.env.XYTolerance = ""
arcpy.env.tinSaveVersion = "CURRENT"
arcpy.env.nodata = "NONE"
arcpy.env.MDomain = ""
arcpy.env.spatialGrid1 = "0"
arcpy.env.cellSize = "MAXOF"
arcpy.env.outputZValue = ""
arcpy.env.outputMFlag = "Same As Input"
arcpy.env.geographicTransformations = ""
arcpy.env.spatialGrid2 = "0"
arcpy.env.ZResolution = ""
arcpy.env.mask = ""
arcpy.env.spatialGrid3 = "0"
arcpy.env.maintainSpatialIndex = "false"
arcpy.env.workspace = "\\\\WURNET.NL\\Homes\\boeke015\\My Documents\\ArcGIS\\Default.gdb"
arcpy.env.MResolution = ""
arcpy.env.derivedPrecision = "HIGHEST"
arcpy.env.ZTolerance = ""

# Local variables:
ForLossYear_shp = "C:\\D\\STACK\\Admin\\Werk\\2018-XXXX PPS\\PROJECTS\\TRADE\\Data\\3_Output\\ForobsTMF_m2.shp"
Cellsize         = "5000"

#field_values = ["Fobs_10", "Fobs_12", "Fobs_21", "Fobs_22", "Fobs_23", "Fobs_24", "Fobs_25", "Fobs_26", "Fobs_31", "Fobs_32", "Fobs_33", "Fobs_41", "Fobs_42", "Fobs_51", "Fobs_52", "Fobs_53", "Fobs_54", "Fobs_61", "Fobs_62", "Fobs_63", "Fobs_64", "Fobs_65", "Fobs_66", "Fobs_67", "Fobs_71", "Fobs_72", "Fobs_73", "Fobs_74", "Fobs_81", "Fobs_82", "Fobs_83", "Fobs_84"]
field_values = ["Fobs_85", "Fobs_86", "Fobs_91", "Fobs_92", "Fobs_93", "Fobs_94"]

for VALUE_FIELD in field_values:
    
    print(VALUE_FIELD)
    
    Fobs_ras    = "C:\\D\\STACK\\Admin\\Werk\\2018-XXXX PPS\\PROJECTS\\TRADE\\Data\\2_Intermediate\\" + VALUE_FIELD + ".tif"

    # Process: Polygon to Raster
    arcpy.PolygonToRaster_conversion(ForLossYear_shp, VALUE_FIELD, Fobs_ras, "CELL_CENTER", "NONE", Cellsize)









